<a href="https://colab.research.google.com/github/Rudra-rudie/pytorch/blob/main/nnbuilding02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self,num_feature):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )

    def forward(self, features):
      out = self.network(features)


      return out

In [ ]:
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self,num_feature):
        super().__init__()
        self.linear = nn.Linear(num_feature, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()


    def forward(self, feature):
      out = self.linear(feature) # FIX: Changed from self.linear1 to self.linear
      out = self.relu(out)
      out = self.linear2(out)
      out = self.sigmoid(out)

      return out

#create dataset
features = torch.rand(10,5)
#create model
model = Model(features.shape[1])

#call model for forward pass
model(features)

tensor([[0.3871],
        [0.4165],
        [0.4316],
        [0.4196],
        [0.3770],
        [0.4404],
        [0.4393],
        [0.3956],
        [0.3934],
        [0.3880]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear2.bias

Parameter containing:
tensor([-0.2423], requires_grad=True)

In [ ]:
model.linear.weight

Parameter containing:
tensor([[ 0.3895,  0.2488, -0.3580, -0.0555, -0.1788],
        [-0.1825,  0.4172, -0.2448,  0.2391,  0.3870],
        [-0.2546, -0.2814,  0.1421,  0.2872,  0.3180]], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00