<a href="https://colab.research.google.com/github/Rudra-rudie/pytorch/blob/main/pipelineTrn01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/prashant-kikani/breast-cancer-detection/master/breast-cancer-data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [ ]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:, 1:], df.iloc[:,0],test_size=0.2)

In [ ]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)


In [ ]:
x_train

array([[-1.10491102, -0.7384608 , -1.12312711, ..., -1.40776753,
        -0.36340912, -0.55733285],
       [ 3.77357675,  0.56629129,  3.76812767, ...,  2.32466735,
        -0.07629843, -0.1923903 ],
       [-0.6517024 , -0.49972899, -0.66704556, ..., -0.40758651,
        -1.1197407 , -1.28721794],
       ...,
       [-0.6921159 , -0.45245536, -0.6800286 , ..., -0.23177403,
        -0.69645752, -0.36604525],
       [ 0.0411006 , -0.62736778, -0.07652675, ..., -1.26272986,
        -0.72927017, -1.24073185],
       [-0.08013992, -0.77155234, -0.15107451, ..., -0.9240547 ,
        -0.88677089, -0.7101492 ]])

In [ ]:
y_train

546    B
180    M
275    B
320    B
165    B
      ..
151    B
370    M
530    B
270    B
357    B
Name: diagnosis, Length: 455, dtype: object

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,

In [ ]:
x_train_tensor = torch.from_numpy(x_train).float()
x_test_tensor = torch.from_numpy(x_test).float()
y_train_tensor = torch.from_numpy(y_train).long()
y_test_tensor = torch.from_numpy(y_test).long()

In [ ]:
x_train_tensor.shape

torch.Size([455, 30])

In [ ]:
x_train_tensor

tensor([[-1.1049, -0.7385, -1.1231,  ..., -1.4078, -0.3634, -0.5573],
        [ 3.7736,  0.5663,  3.7681,  ...,  2.3247, -0.0763, -0.1924],
        [-0.6517, -0.4997, -0.6670,  ..., -0.4076, -1.1197, -1.2872],
        ...,
        [-0.6921, -0.4525, -0.6800,  ..., -0.2318, -0.6965, -0.3660],
        [ 0.0411, -0.6274, -0.0765,  ..., -1.2627, -0.7293, -1.2407],
        [-0.0801, -0.7716, -0.1511,  ..., -0.9241, -0.8868, -0.7101]],
       dtype=torch.float64)

In [ ]:
y_train_tensor.shape

torch.Size([455])

In [ ]:
from torch.utils.data import TensorDataset, DataLoader, Dataset

class CustomDataset(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self, idx):
    return self.features[idx], self.labels[idx]


In [ ]:
train_dataset = CustomDataset(x_train_tensor, y_train_tensor)
test_dataset = CustomDataset(x_test_tensor, y_test_tensor)

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from torch.utils.data import TensorDataset, DataLoader, Dataset

# Re-loading the dataset and dropping columns
df = pd.read_csv('https://raw.githubusercontent.com/prashant-kikani/breast-cancer-detection/master/breast-cancer-data.csv')
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

# Split the data into features (X) and target (y)
X = df.iloc[:, 1:]
y = df.iloc[:,0]

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale the features
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

# Encode the labels
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

# Convert numpy arrays to PyTorch tensors
x_train_tensor = torch.from_numpy(x_train).float()
x_test_tensor = torch.from_numpy(x_test).float()
y_train_tensor = torch.from_numpy(y_train).long()
y_test_tensor = torch.from_numpy(y_test).long()

# Define the CustomDataset class
class CustomDataset(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self, idx):
    return self.features[idx], self.labels[idx]

# Create CustomDataset instances
train_dataset = CustomDataset(x_train_tensor, y_train_tensor)
test_dataset = CustomDataset(x_test_tensor, y_test_tensor)

print("Data preprocessing and datasets created successfully!")

Data preprocessing and datasets created successfully!


In [ ]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

In [ ]:
learning_rate=0.1
epochs = 25

In [ ]:
loss_function = nn.BCELoss()

In [ ]:
model = MySimpleNN(x_train_tensor.shape[1])
model.linear.weight

Parameter containing:
tensor([[-0.1236, -0.1273, -0.0984, -0.1596,  0.0757, -0.0478,  0.0159,  0.0994,
          0.0382,  0.0875,  0.1687,  0.1418, -0.0907,  0.0255, -0.1024, -0.0958,
         -0.0363,  0.1065, -0.0751,  0.1414, -0.0345,  0.1187, -0.0140,  0.1136,
          0.1584,  0.1756, -0.0462, -0.0919,  0.0331, -0.0846]],
       requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([-0.0830], requires_grad=True)

In [ ]:
model = MySimpleNN(x_train_tensor.shape[1])
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

#define loop
for epoch in range(epochs):

    #forward pass
    y_pred = model.forward(x_train_tensor)

    #loss calculations
    # Ensure y_train_tensor is float and reshaped for the loss calculation
    loss = loss_function(y_pred, y_train_tensor.float().unsqueeze(1))
    print(f'Epoch:{epoch+1}, Loss:{loss.item()}')

    #backward pass
    loss.backward()

    #parameter update
    optimizer.step()
    #zeros gradients
    optimizer.zero_grad()

Epoch:1, Loss:0.8936578631401062
Epoch:2, Loss:0.6489584445953369
Epoch:3, Loss:0.5221731066703796
Epoch:4, Loss:0.4475330412387848
Epoch:5, Loss:0.397893488407135
Epoch:6, Loss:0.3620404005050659
Epoch:7, Loss:0.3346398174762726
Epoch:8, Loss:0.31283167004585266
Epoch:9, Loss:0.294939249753952
Epoch:10, Loss:0.2799111306667328
Epoch:11, Loss:0.2670522928237915
Epoch:12, Loss:0.25588351488113403
Epoch:13, Loss:0.2460624724626541
Epoch:14, Loss:0.23733745515346527
Epoch:15, Loss:0.2295188307762146
Epoch:16, Loss:0.22246050834655762
Epoch:17, Loss:0.21604783833026886
Epoch:18, Loss:0.21018943190574646
Epoch:19, Loss:0.20481127500534058
Epoch:20, Loss:0.19985273480415344
Epoch:21, Loss:0.19526347517967224
Epoch:22, Loss:0.1910012811422348
Epoch:23, Loss:0.18703049421310425
Epoch:24, Loss:0.18332064151763916
Epoch:25, Loss:0.17984549701213837


In [ ]:
import torch.nn as nn

# Define the neural network model (assuming MySimpleNN was intended to be a simple linear model)
class MySimpleNN(nn.Module):
    def __init__(self, input_dim):
        super(MySimpleNN, self).__init__()
        self.linear = nn.Linear(input_dim, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.linear(x)
        x = self.sigmoid(x)
        return x

# Define hyperparameters
learning_rate = 0.1
epochs = 25

# Initialize model, loss function, and optimizer
model = MySimpleNN(x_train_tensor.shape[1])
loss_function = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# Training loop
for epoch in range(epochs):
    for batch_features, batch_labels in train_loader:
        # Forward pass
        y_pred = model(batch_features)

        # Calculate loss
        loss = loss_function(y_pred, batch_labels.float().unsqueeze(1))

        # Backward pass and optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    print(f'Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}')


Epoch [1/25], Loss: 0.1895
Epoch [2/25], Loss: 0.2404
Epoch [3/25], Loss: 0.0955
Epoch [4/25], Loss: 0.0490
Epoch [5/25], Loss: 0.0484
Epoch [6/25], Loss: 0.1921
Epoch [7/25], Loss: 0.1702
Epoch [8/25], Loss: 0.0474
Epoch [9/25], Loss: 0.0471
Epoch [10/25], Loss: 0.0557
Epoch [11/25], Loss: 0.0579
Epoch [12/25], Loss: 0.0189
Epoch [13/25], Loss: 0.0152
Epoch [14/25], Loss: 0.1336
Epoch [15/25], Loss: 0.0034
Epoch [16/25], Loss: 0.7085
Epoch [17/25], Loss: 0.0461
Epoch [18/25], Loss: 0.1147
Epoch [19/25], Loss: 0.0114
Epoch [20/25], Loss: 0.1077
Epoch [21/25], Loss: 0.1073
Epoch [22/25], Loss: 0.0547
Epoch [23/25], Loss: 0.0333
Epoch [24/25], Loss: 0.0132
Epoch [25/25], Loss: 0.0490


In [ ]:
model.linear.weight

Parameter containing:
tensor([[ 0.1195,  0.1195, -0.1075,  0.1735,  0.1186,  0.0623,  0.1165,  0.0771,
         -0.1317,  0.0226, -0.1799, -0.1078, -0.1569, -0.0938,  0.1438, -0.0855,
         -0.1728, -0.1176,  0.1060, -0.0285, -0.0317, -0.1555, -0.0208,  0.0281,
         -0.1225,  0.1128, -0.1697,  0.0623,  0.0725, -0.0912]],
       requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([-0.0501], requires_grad=True)

In [ ]:
model.eval()
accuracy_list = [] # Removed redundant initialization

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        y_pred = model(batch_features)
        # Correcting the prediction thresholding and type casting.
        # Assuming 0.5 as the threshold for binary classification and converting to long.
        # .squeeze(1) is used to match the shape of batch_labels (e.g., [batch_size] vs [batch_size, 1]).
        y_pred_classified = (y_pred > 0.5).long().squeeze(1)

        # Calculate batch accuracy
        batch_accuracy = (y_pred_classified == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

    # Correcting indentation and the length calculation
    overall_accuracy = sum(accuracy_list) / len(accuracy_list)
    print(f'Accuracy: {overall_accuracy:.4f}')

Accuracy: 0.9861
